# Generated by Django 5.1 on 2025-09-18 10:12

import autoslug.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coname", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "credit_limit",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_dashboard", "Can view dashboard"),
                    ("view_balance_sheet", "Can view balance sheet"),
                    ("view_store", "Can view store"),
                    ("view_reports", "Can view reports"),
                    ("view_inventory", "Can view inventory"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fname", models.CharField(max_length=255)),
                ("cnic", models.CharField(max_length=13)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Accontant", "Accontant"),
                            ("Purchaser", "Purchaser"),
                            ("Office Boy", "Office Boy"),
                            ("Security Guard", "Security Guard"),
                            ("Driver", "Driver"),
                            ("Machine Operator", "Machine Operator"),
                            ("Foreman", "Foreman"),
                            ("Labour Incharge", "Labour Incharge"),
                            ("Fitter", "Fitter"),
                            ("Sweeper", "Sweeper"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("salary", models.PositiveIntegerField()),
                ("instalment", models.PositiveIntegerField()),
                ("order", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("All Type", "All Type"),
                            ("Contractors", "Contractors"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Finish_Product_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("vehicle", models.CharField(max_length=255)),
                ("driver_phone_number", models.CharField(max_length=20)),
                ("dispatch_for", models.CharField(max_length=255)),
                ("name_of_site", models.CharField(max_length=255)),
                ("person_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("returnable", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Price_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coname", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("adress", models.CharField(max_length=255)),
                (
                    "contact",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("description", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UnderConstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_under_construction",
                    models.BooleanField(
                        blank=True, help_text="Note for Under Costruction", null=True
                    ),
                ),
                (
                    "uc_note",
                    models.TextField(
                        blank=True, help_text="Note for under construction", null=True
                    ),
                ),
                (
                    "uc_duration",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date and time for under construction mode",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cheque_amount",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cheque_date", models.DateField()),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Final_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=255, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("Nos", "Nos"), ("Kgs", "Kgs")],
                        default="Nos",
                        max_length=50,
                    ),
                ),
                ("purchase", models.PositiveIntegerField(blank=True, null=True)),
                ("sale_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("labour", models.FloatField(blank=True, null=True)),
                ("product_status", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "product_slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="productname",
                        unique=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.company"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.finish_product_category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Final_Product_Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Final_Product_Note_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "final_product_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.final_product_note",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.final_product",
                    ),
                ),
            ],
            options={
                "unique_together": {("final_product_note", "product")},
            },
        ),
        migrations.AddField(
            model_name="final_product_note",
            name="products",
            field=models.ManyToManyField(
                through="home.Final_Product_Note_Product", to="home.final_product"
            ),
        ),
        migrations.CreateModel(
            name="Final_Product_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="final_product_price",
                        to="home.final_product",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="final_pro_price",
                        to="home.price_list",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="price_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.price_list"
            ),
        ),
        migrations.CreateModel(
            name="Price_List_Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_note",
                        to="home.price_list",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price_List_Note_Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.price_list",
                    ),
                ),
                (
                    "price_list_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.price_list_note",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.final_product",
                    ),
                ),
            ],
            options={
                "unique_together": {("price_list", "product")},
            },
        ),
        migrations.AddField(
            model_name="price_list_note",
            name="products",
            field=models.ManyToManyField(
                through="home.Price_List_Note_Products", to="home.final_product"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=255, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("Nos", "Nos"), ("Kgs", "Kgs")],
                        default="Nos",
                        max_length=50,
                    ),
                ),
                (
                    "default_store",
                    models.CharField(
                        choices=[
                            ("Store1", "Store1"),
                            ("Store2", "Store2"),
                            ("Store3", "Store3"),
                        ],
                        default="Store1",
                        max_length=50,
                    ),
                ),
                ("stockable", models.BooleanField(default=False)),
                ("rate", models.FloatField(blank=True, default=0, null=True)),
                ("labour", models.FloatField(blank=True, default=0, null=True)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                (
                    "stock",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("product_status", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "product_slug",
                    autoslug.fields.AutoSlugField(default=None, null=True, unique=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.category"
                    ),
                ),
                (
                    "final_product_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.finish_product_category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GatePassProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gatepass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.gatepass"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gatepass",
            name="products",
            field=models.ManyToManyField(
                through="home.GatePassProduct", to="home.product"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="home.region"
            ),
        ),
        migrations.CreateModel(
            name="Sales_Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("customer", models.CharField(blank=True, max_length=220, null=True)),
                ("phone_number", models.CharField(max_length=12)),
                ("make_transaction", models.BooleanField(default=False)),
                ("is_cash", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales_Receipt_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.FloatField()),
                ("amount", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.final_product",
                    ),
                ),
                (
                    "salereceipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sales_receipt_products",
                        to="home.sales_receipt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sales_receipt",
            name="products",
            field=models.ManyToManyField(
                through="home.Sales_Receipt_Product", to="home.final_product"
            ),
        ),
        migrations.CreateModel(
            name="Store_Issue_Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_issue_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_issue_notes",
                        to="home.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store_Issue_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issued_in_notes",
                        to="home.product",
                    ),
                ),
                (
                    "store_issue_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="store_issue_products",
                        to="home.store_issue_note",
                    ),
                ),
            ],
            options={
                "unique_together": {("store_issue_note", "product")},
            },
        ),
        migrations.AddField(
            model_name="store_issue_note",
            name="products",
            field=models.ManyToManyField(
                through="home.Store_Issue_Product", to="home.product"
            ),
        ),
        migrations.CreateModel(
            name="Store_Issue_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("issue", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_requests",
                        to="home.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store_issue_note",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requested_issue_notes",
                to="home.store_issue_request",
            ),
        ),
        migrations.CreateModel(
            name="Store_Issue_Request_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.product"
                    ),
                ),
                (
                    "store_issue_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="store_issue_request_products",
                        to="home.store_issue_request",
                    ),
                ),
            ],
            options={
                "unique_together": {("store_issue_request", "product")},
            },
        ),
        migrations.AddField(
            model_name="store_issue_request",
            name="products",
            field=models.ManyToManyField(
                through="home.Store_Issue_Request_Product", to="home.product"
            ),
        ),
        migrations.CreateModel(
            name="Store_Purchase_Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store_Purchase_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.product"
                    ),
                ),
                (
                    "store_purchase_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.store_purchase_note",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store_purchase_note",
            name="products",
            field=models.ManyToManyField(
                through="home.Store_Purchase_Product", to="home.product"
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Asset", "Asset"),
                            ("Liability", "Liability"),
                            ("Equity", "Equity"),
                            ("Revenue", "Revenue"),
                            ("Expense", "Expense"),
                            ("Gain", "Gain"),
                            ("Loss", "Loss"),
                            ("Commitment", "Commitment"),
                            ("Commitment_Received", "Commitment_Received"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 9, 18, 15, 12, 2, 126712)
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "cheque",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.cheque",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.customer",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.employee",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.suppliers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="home.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="product_price",
                        to="home.product",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="home.region",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "customer")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "credit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="credit_transactions",
                        to="home.account",
                    ),
                ),
                (
                    "debit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="debit_transactions",
                        to="home.account",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["debit_account"], name="home_transa_debit_a_0e4eda_idx"
                    ),
                    models.Index(
                        fields=["credit_account"], name="home_transa_credit__33a65f_idx"
                    ),
                    models.Index(fields=["date"], name="home_transa_date_a8ccfc_idx"),
                ],
            },
        ),
    ]
