# Generated by Django 5.2.5 on 2025-10-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_account_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='final_product',
            name='labour',
        ),
        migrations.RemoveField(
            model_name='final_product',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='final_product',
            name='sale_rate',
        ),
        migrations.RemoveField(
            model_name='final_product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 19, 13, 35, 807456)),
        ),
    ]
