# Generated by Django 5.1 on 2025-10-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_account_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 26, 11, 57, 25, 165801)
            ),
        ),
    ]
