# Generated by Django 5.2.7 on 2025-11-19 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_account_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 11, 35, 36, 906895)
            ),
        ),
    ]
