# Generated by Django 5.1 on 2025-10-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_account_date"),
        ("home", "0003_remove_final_product_company_and_more"),
    ]

    operations = []
