# Generated by Django 5.2.5 on 2025-11-09 03:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_final_product_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Item_Category',
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 8, 12, 49, 458187)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='products',
            field=models.ManyToManyField(through='home.GatePassProduct', to='home.final_product'),
        ),
        migrations.AlterField(
            model_name='gatepassproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.final_product'),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_price', to='home.final_product'),
        ),
        migrations.AlterField(
            model_name='sales_receipt',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
