# Generated by Django 5.2.7 on 2025-11-19 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_account_active_transaction_transaction_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 12, 19, 56, 927395)
            ),
        ),
    ]
