# Generated by Django 5.2.7 on 2025-11-19 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_account_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_receipt",
            name="transaction_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 12, 22, 43, 630504)
            ),
        ),
    ]
