# Generated by Django 5.2.7 on 2025-11-19 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_sales_receipt_transaction_ref_alter_account_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash Received", "Cash Payed"),
                    ("Cash Payed", "Liability"),
                    ("Sales", "Sales"),
                    ("Amount Transfer", "Amount Transfer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 19, 12, 39, 14, 476524)
            ),
        ),
    ]
