# Generated by Django 5.2.5 on 2025-11-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_item_rename_category_item_category_and_more'),
        ('home', '0006_transaction_transaction_type_alter_account_date'),
    ]

    operations = [
    ]
