# Generated by Django 5.1 on 2025-11-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_merge_20251026_1929"),
        ("home", "0006_transaction_transaction_type_alter_account_date"),
    ]

    operations = []
