# Generated by Django 5.1 on 2025-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_product_item_rename_category_item_category_and_more"),
        ("home", "0007_merge_20251119_1312"),
    ]

    operations = []
