# Generated by Django 5.2.7 on 2025-11-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_merge_20251126_1806"),
        ("home", "0008_merge_20251126_1813"),
    ]

    operations = []
