# Generated by Django 5.2.7 on 2025-11-27 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_merge_20251127_1038"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cheque",
            old_name="cheque_date",
            new_name="cheque_duedate",
        ),
        migrations.RemoveField(
            model_name="cheque",
            name="status",
        ),
        migrations.AddField(
            model_name="cheque",
            name="cleared_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cheque",
            name="is_cleared",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 27, 10, 54, 51, 378103)
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash Received", "Cash Payed"),
                    ("Cash Payed", "Cash Recieved"),
                    ("Sales", "Sales"),
                    ("Account to Account", "Account to Account"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
