# Generated by Django 5.2.7 on 2025-11-27 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_rename_cheque_date_cheque_cheque_duedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="cheque_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="is_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash Received", "Cash Payed"),
                    ("Cash Payed", "Cash Recieved"),
                    ("Sales", "Sales"),
                    ("Account to Account", "Account to Account"),
                    ("Commitment", "Commitment"),
                    ("Commitment Received", "Commitment Received"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
