# Generated by Django 5.2.7 on 2025-11-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_cheque_remaining_amount_alter_account_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
