# Generated by Django 5.2.7 on 2025-11-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_account_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="auto_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_for_cheque_payment",
                to="home.transaction",
            ),
        ),
    ]
