# Generated by Django 5.2.7 on 2025-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_cheque_auto_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cheque",
            name="auto_transaction",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash Received", "Cash Received"),
                    ("Cash Payed", "Cash Payed"),
                    ("Sales", "Sales"),
                    ("Account to Account", "Account to Account"),
                    ("Commitment", "Commitment"),
                    ("Commitment Received", "Commitment Received"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
