# Generated by Django 5.2.7 on 2025-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_cheque_auto_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="auto",
            field=models.BooleanField(default=False),
        ),
    ]
